### ISSUE TITLE
Change name of python package to mwmbl

### ISSUE THREAD

**Issue by nitred** [mwmbl/mwmbl#15]
As discussed with @daoudclarke it might be best to change the name of the package from `tinysearchengine` to `mwmbl`. Also it would be good to nest the `tinysearchengine` and `indexer` modules within a `mwmbl` root module.

**It has the following advantages**:
* In the future you could break the repo into two separate repos like `mwmbl-tinysearchengine` and `mwmbl-indexer` but imports will not have to change if we follow conventions for [namespaces pacakges](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/).
* `mwmbl` can be released as a python package on pypi.org
* We can have official named entrypoints (i.e. named CLI scripts) which are auto installed when you install the mwmbl package using `pip install mwmbl`.
* There are other more subtle advantages that come from mwmbl being a python package such as easy testing and dependency management.

**TODO**

* [ ] Change the name of the project from `tinysearchengine` to `mwmbl` in `pyproject.toml`
* [ ] Change the project directory to look like the following
    ```
    mwmbl                        # repository root
    -- pyproject.toml
    -- poetry.lock
    -- mwmbl                     # new python package folder (this can eventually become the namespace name)
    ---- __init__.py
    ---- tinysearchengine        # tinysearchengine becomes a module within mwmbl
    ------ __init__.py
    ------ ...
    ---- indexer                 # indexer becomes a module within mwmbl
    ------ __init__.py
    ------ ....
    ```
* [ ] Change all import statements to include the new package structure. For example `from tinysearchengine import create_app` will become `from mwmbl.tinysearchengine import create_app`
